#+TITLE: My GNU Emacs Configuration
#+DATE: Wednesday, September 25, 2024
#+PROPERTY: header-args:emacs-lisp :results silent
#+STARTUP: overview

* Introduction

This is my literate Emacs configuration file; there are many like it,
but this one is mine. It serves as both documentation and the source
for configuring Emacs. All necessary config files are generated from
this file by calling ~org-babel-tangle~ (~C-c C-v t~), and stored in the
=/modules= sub-directory. As such, changes should be made in this
document, not in the individual config files.

*N.B.* Modules are individually imported in [[*Conclusion][Conclusion]].

* early-init.el

The =early-init.el= file, introduced with Emacs27, is the first file
that Emacs reads when starting up (before =init.el=). In principal, the
early initialization file should set-up a few basic things before
Emacs produces the initial frame, and should not depend on any
packages.

#+begin_src emacs-lisp :tangle early-init.el
;;; -*- lexical-binding: t -*-
#+end_src

** Temporarily Configure Garbage Collection

Garbage collection (GC) ensures that a program does not exceed its
memory quote or reach a point that it can no longer function. It also
frees up developers from having to manually manage a program's memory
which, in turn, reduces the potential for memory-related bugs.

However, GC can extend startup time. Therefore, we (temporarily) set
~gc-cons-threshold~ to a very large number -- effectively disabling
garbage collection. Otherwise Emacs might freeze. This strategy is
used by =Doom-Emacs= [[[https://github.com/doomemacs/doomemacs/blob/master/early-init.el][doomemacs/early-init.el]]].

*N.B.* This value is reset later in [[*Reset Garbage Collection][Reset Garbage Collection]].

#+begin_src emacs-lisp :tangle early-init.el
;; Temporarily increase garbage collect for fast startup
(setq gc-cons-threshold most-positive-fixnum)
#+end_src

** Disable Frame Resizing

Changing the font, bars, and fringes may resize the frame in order to
preserve the number of oclumns or lines it displays. It is said that
this affects startup times.

Set prior to [[*Disable UI Elements][Disable UI Elements]] as those changes may affect frame
resizing?

+ Damien Cassou :: [[https://github.com/DamienCassou/emacs.d/blob/master/early-init.el#L25][github.com/early-init.el]]
+ Tony Zorman :: [[https://tony-zorman.com/posts/emacs-potpourri.html][A Potpourri of Emacs Tweaks]]

#+begin_src emacs-lisp :tangle early-init.el
;; Inhibit frame resizing due to visual settings
(setq frame-inhibit-implied-resize t)

#+end_src

** Disable UI Elements

#+begin_src emacs-lisp :tangle early-init.el
;; Prevent gimpse of un-styled Emacs
(menu-bar-mode   -1)
(scroll-bar-mode -1) ; Visible scrollbar
(scroll-all-mode -1) ; Synchronized scrolling of buffers
(tool-bar-mode   -1)
(tooltip-mode    -1)

;; No need for splash screen and echo area message
(setq-default inhibit-startup-screen t     ; disable start-up screen
              inhibit-startup-message t    ; disable start-up message
              initial-scratch-message nil  ; Empty initial *scratch* buffer
              initil-buffer-choice t       ; Open *scratch* buffer at init
              initial-major-mode 'fundamental-mode)
#+end_src

* init.el

#+begin_src emacs-lisp :tangle init.el
;;; -*- lexical-binding: t -*-

;; Profile emacs startup
(add-hook 'emacs-startup-hook
          (lambda ()
            (message "*** Emacs loaded in %s seconds with %d garbage collections."
                     (emacs-init-time "%.2f")
                     gcs-done)))
#+end_src

** Initialize Package Resources

#+begin_src emacs-lisp :tangle init.el
;; Initialize package resources
(require 'package)
(setq package-archives
      '(("gnu elpa"  . "https://elpa.gnu.org/packages/")
        ("melpa"     . "https://melpa.org/packages/")
        ("nongnu"    . "https://elpa.nongnu.org/nongnu/"))
      package-archive-priorities
      '(("melpa"    . 6)
        ("gnu elpa" . 5)
        ("nongnu"   . 4)))
(package-initialize)
#+end_src

** Setup 'use-package'

#+begin_src emacs-lisp :tangle init.el
;; Is this still necessary since 'use-package' now builtin?
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

;; Standardize `use-package` settings
(require 'use-package-ensure)
(setq use-package-always-ensure t
      use-package-compute-statistics t
      use-package-verbose t)
#+end_src

** Tidy Emacs Directory

Default paths used to store configuraiton files and persistent data
are not consistent across Emacs packages, and are often dumped into
~user-emacs-directory~. Alternatively, the =no-littering= package stores
config and data files in =/etc= and =/var= sub-directories of
~user-emacs-directory~.

#+begin_src emacs-lisp :tangle init.el
(use-package no-littering
  :demand t
  :config
  ;; Save customizations in 'etc' sub-directory and load on startup
  (setq custom-file (no-littering-expand-etc-file-name "custom.el"))
  (when (file-exists-p custom-file)
    (load custom-file)))
#+end_src

** Reset Garbage Collection

In [[*Temporarily Configure Garbage Collection][Temporarily Configure Garbage Collection]] we maximized GC thresholds
to improve startup time. Here, we use =Doom-Emacs=' "Garbage Collection
Magic Hack" package [[[https://github.com/emacsmirror/gcmh][github/gcmh]]] to reset these values and enforce a
"sneaky" GC strategy.

#+begin_src emacs-lisp :tangle init.el
;; Garbage Collection Magic Hack
(use-package gcmh
  :init (gcmh-mode 1)
  :hook
  (after-init . garbage-collect)

  ;; Must reset GC threshold values after initialization
  (emacs-startup . (lambda () (setq gc-cons-percentage 0.1
                                    gc-cons-threshold (* 32 1024 1024)
                                    gcmh-high-cons-threshold (* 32 1024 1024)
                                    gcmh-idle-delay 30))))
#+end_src

It is recommended that we perform garbage collection when not actively
using Emacs. Therefore, we perform GC if idle for 30 seconds.(credit:
[[https://emacs.stackexchange.com/questions/34342/is-there-any-downside-to-setting-gc-cons-threshold-very-high-and-collecting-ga][StackExchange]])

#+begin_src emacs-lisp :tangle init.el
;; Idle garbage collecting
(run-with-idle-timer 30 t (lambda () (garbage-collect)))
#+end_src

** Better Defaults

Here, we configure default built-in Emacs settings.

*** Frame

#+begin_src emacs-lisp :tangle init.el
;; Change frame title w.r.t. current buffer
(setq frame-title-format
      '("emacs: " (:eval (if (buffer-file-name)
                             (abbreviate-file-name (buffer-file-name)) "%b"))))

;; Maximize frame size at init
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src
*** Prompts

#+begin_src emacs-lisp :tangle init.el
;; Too lazy to type 'yes-or-no'
(setq use-short-answers t)
(fset 'yes-or-no-p 'y-or-n-p)

;; Kill buffer, even if live process attached
;; https://www.masteringemacs.org/article/disabling-prompts-emacs
(setq kill-buffer-query-functions
      (remq 'process-kill-buffer-query-function
            kill-buffer-query-functions))
#+end_src

*** Mini-Buffer
**** Recursive Minibuffer

#+begin_src emacs-lisp :tangle modules/my-completion.el
;; Support opening new minibuffers from inside existing minibuffers
(setq enable-recursive-minibuffers t)
#+end_src

**** Prompt Indicator to 'completing-read-multiple'

Recommended in the configuration of =vertico= package [[[https://github.com/minad/vertico][github/vertico]]],
the custom function ~crm-indicator~ adds an indicator to the completion
prompt when using ~completing-read-multiple~ which can be useful for
visually distinguishing prompts or results.

#+begin_src emacs-lisp :tangle modules/my-completion.el
(defun crm-indicator (args)
  "Add indicator to completion promp when using 'completing-read-multiple'"
  (cons (format "[CRM%s] %s"
                (replace-regexp-in-string
                 "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                 crm-separator)
                (car args))
        (cdr args)))
(advice-add #'completing-read-multiple :filter-args #'crm-indicator)
#+end_src

For example, calling the example function ~test-crm-indicator~ indicates
that selecting multiple options is both possible using a
comma-separator. *N.B.* src-block not tangled to configuration file.

#+begin_src emacs-lisp :tangle no
(defun test-crm-indicator ()
  "A custom function using completing-read-multiple."
  (interactive)
  (let ((choices '("Option A" "Option B" "Option C")))
    (completing-read-multiple "Choose options: " choices)))
#+end_src

**** Make Minibuffer Prompt Read-Only

Again, recommended in the configuration of the =vertico= package
[[[https://github.com/minad/vertico][github/vertico]]]. This code defines the minibuffer prompt to be
read-only and makes the cursor intangible when it is over the
minibuffer prompt. In other words, text in the minibuffer cannot be
selected or modified by the cursor. This can be useful for creating a
visually distinct and non-editable minibuffer prompt.

#+begin_src emacs-lisp :tangle modules/my-completion.el
(setq minibuffer-prompt-properties
      '(read-only t cursor-intangible t face minibuffer-prompt))
(add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)
#+end_src

For example if ~(setq minibuffer-prompt-properties nil)~ and we call
~M-x~, it would be possible to modify the prompt by moving the cursor
back ~C-b~ and deleting M, -, or x. _Not ideal_.

**** Close Minibuffer Regardless of Point Location

#+begin_src emacs-lisp :tangle init.el
;; Closes minibuffer regardless of point location
(advice-add 'keyboard-quit :before (lambda ()
                                     (when (active-minibuffer-window)
                                       (abort-recursive-edit))))
#+end_src
*** Indentation Style

#+begin_src emacs-lisp :tangle init.el
;; Disable 'TAB' for indentation
(setq-default indent-tabs-mode nil)

;; Use 'TAB' for auto-completion selection
(setq-default tab-always-indent 'complete)

;; Number of spaces occupied by 'TAB'
(setq-default tab-width 4
              standard-indent 4)
#+end_src

*** Whitespace

The builtin =whitespace-mode= is useful for visualizing and
automatically cleaning up white-spaces in our buffers. [[https://www.emacswiki.org/emacs/WhiteSpace][Emacswiki]]
provides a nice overview of the settings.

The ~whitespace-style~ variable specifies how blank white-spaces are
visualized and the following are included in our configuration:

  + face :: Enable all visualization via faces. Required for
    visualization of many white-spaces listed below.
  + trailing :: Trailing blanks are visualized via faces.
  + lines-tail :: Columns beyond ~whitespace-line-column~ are
    highlighted via faces (must exclude =lines= in our configuration).
  + empty :: Empty lines at beginning/end of buffer are visualized.
  + indentation::space :: TABs at beginning of lines are visualized.
  + space-before-tab::tab :: SPACEs before TAB are visualized.

#+begin_src emacs-lisp :tangle init.el
;; Built-in Emacs variable highlights empty lines
(setq indicate-empty-lines t)

;; Visualize whitespace and remove on cleanup
(use-package whitespace
  :hook (((prog-mode org-mode) . whitespace-mode)
         (before-save . whitespace-cleanup))
  :custom
  (whitespace-line-column 79 "Highlight text beyond column")
  (whitespace-style '(face
                      trailing
                      lines-tail
                      empty
                      indentation::space
                      space-before-tab::tab))
  :config
  ;; Turn off global whitespace mode
  (global-whitespace-mode 0))
#+end_src

*** Mouse/Scrolling

#+begin_src emacs-lisp :tangle init.el
(setq  mouse-wheel-scroll-amount '(1 ((shift) . 1)) ; scroll one line at a time
       mouse-wheel-progressive-speed nil            ; don't accelerate scrolling
       mouse-wheel-follow-mouse 't                  ; scroll window under mouse
       mouse-yank-at-point t)                       ; Mouse paste at point, not cursor

;; Scrolling at end of document adds one line
(setq scroll-step 1)

;; Use pixel scrolling instead of by line
;; https://tony-zorman.com/posts/emacs-potpourri.html
(pixel-scroll-precision-mode 1)
#+end_src

*** Cursor

#+begin_src emacs-lisp :tangle init.el
(setq-default cursor-type 'bar)

;; Flash cursor location when switching buffers
(use-package beacon
  :config (beacon-mode 1))
#+end_src

*** Writing

#+begin_src emacs-lisp :tangle init.el
;; Replace active region by typing text
(delete-selection-mode 1)
#+end_src

