#+TITLE: My GNU Emacs Configuration
#+DATE: Wednesday, September 25, 2024
#+PROPERTY: header-args:emacs-lisp :results silent
#+STARTUP: overview

* Introduction

This is my literate Emacs configuration file; there are many like it,
but this one is mine. It serves as both documentation and the source
for configuring Emacs. All necessary config files are generated from
this file by calling ~org-babel-tangle~ (~C-c C-v t~), and stored in the
=/modules= sub-directory. As such, changes should be made in this
document, not in the individual config files.

*N.B.* Modules are individually imported in [[*Conclusion][Conclusion]].

* early-init.el

The =early-init.el= file, introduced with Emacs27, is the first file
that Emacs reads when starting up (before =init.el=). In principal, the
early initialization file should set-up a few basic things before
Emacs produces the initial frame, and should not depend on any
packages.

#+begin_src emacs-lisp :tangle early-init.el
;;; -*- lexical-binding: t -*-
#+end_src

** Temporarily Configure Garbage Collection

Garbage collection (GC) ensures that a program does not exceed its
memory quote or reach a point that it can no longer function. It also
frees up developers from having to manually manage a program's memory
which, in turn, reduces the potential for memory-related bugs.

However, GC can extend startup time. Therefore, we (temporarily) set
~gc-cons-threshold~ to a very large number -- effectively disabling
garbage collection. Otherwise Emacs might freeze. This strategy is
used by =Doom-Emacs= [[[https://github.com/doomemacs/doomemacs/blob/master/early-init.el][doomemacs/early-init.el]]].

*N.B.* This value is reset later in [[*Reset Garbage Collection][Reset Garbage Collection]].

#+begin_src emacs-lisp :tangle early-init.el
;; Temporarily increase garbage collect for fast startup
(setq gc-cons-threshold most-positive-fixnum)
#+end_src

** Disable Frame Resizing

Changing the font, bars, and fringes may resize the frame in order to
preserve the number of oclumns or lines it displays. It is said that
this affects startup times.

Set prior to [[*Disable UI Elements][Disable UI Elements]] as those changes may affect frame
resizing?

+ Damien Cassou :: [[https://github.com/DamienCassou/emacs.d/blob/master/early-init.el#L25][github.com/early-init.el]]
+ Tony Zorman :: [[https://tony-zorman.com/posts/emacs-potpourri.html][A Potpourri of Emacs Tweaks]]

#+begin_src emacs-lisp :tangle early-init.el
;; Inhibit frame resizing due to visual settings
(setq frame-inhibit-implied-resize t)

#+end_src

** Disable UI Elements

#+begin_src emacs-lisp :tangle early-init.el
;; Prevent gimpse of un-styled Emacs
(menu-bar-mode   -1)
(scroll-bar-mode -1) ; Visible scrollbar
(scroll-all-mode -1) ; Synchronized scrolling of buffers
(tool-bar-mode   -1)
(tooltip-mode    -1)

;; No need for splash screen and echo area message
(setq-default inhibit-startup-screen t     ; disable start-up screen
              inhibit-startup-message t    ; disable start-up message
              initial-scratch-message nil  ; Empty initial *scratch* buffer
              initil-buffer-choice t       ; Open *scratch* buffer at init
              initial-major-mode 'fundamental-mode)
#+end_src

