#+TITLE: Managing Python Virtual Environments
#+DATE: Monday, January 13, 2025
#+STARTUP: overview

* Introduction

This document outlines the tools and procedures necessary for creating and
organizing =python= virtual environments (=venv=).

* Background
** Creating a Virtual Environment

Working with =venv= requires three steps: (1) installing =virtualenv=, (2) creating
the =venv=, and (3) activating it. *N.B.* This assumes =pip= is installed.

*Resources:*
+ [[https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/][packaging.python.org]] :: Installing Using Pip and Virtual Environments


#+begin_src sh
# Install 'virtualenv'
pip install virtualenv

# Create venv
python3 -m venv example_venv

# Activate venv
source <venv-path>/example_venv/bin/activate

# Load packages
...

# Remove venv
rm -r <venv-path>/example_venv
#+end_src

* Preliminaries
** Virtual Environment Manager

=virtualenvwrapper= is an extension that makes creating, deleting, and managing
=venvs= easier. The package centralizes virtual environments in
~$WORKON_HOME=$HOME/.virtualenvs~ and provides user-friendly CLI commands for
managing and switching between =venvs=.

To install on Arch Linux:

#+begin_src sh
# To intsall on Arch Linux:
yay python-virtualenvwrapper
#+end_src

To access the CLI commands every time, the following must be added to =.bashrc=:

#+begin_src sh
source /usr/bin/virtualenvwrapper.sh
source /usr/bin/virtualenvwrapper_lazy.sh
#+end_src

Now, working on =venvs= is much easier:

#+begin_src sh
# Create venv; default location = ~/.virtualenvs
mkvirtualenv example_venv

# Activate venv
workon example_venv

# Load packages
...

# Remove venv
rmvirtualenv example_venv
#+end_src

** Python Package Manager

In python, =pip= is the default package manager used to install, manage, and
remove python libraries and dependencies. However, it is slow. Instead, we will
use [[https://github.com/astral-sh/uv][uv]], an extremely fast alternative written in =Rust=.

#+begin_src sh
# By default, installed to '/home/jon/.local/bin'
curl -LsSf https://astral.sh/uv/install.sh | sh
#+end_src

